services:
  mongodb:
    image: mongo:7
    container_name: reconcile-mongodb
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=invoice-reconciliation

volumes:
  mongodb_data:
